// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7pKaXzhSgIA31wHp2ImNKE2c7pRt6ZeE',
    appId: '1:693823491458:web:75c442d93ee14a63b1539b',
    messagingSenderId: '693823491458',
    projectId: 'le-kpao',
    authDomain: 'le-kpao.firebaseapp.com',
    storageBucket: 'le-kpao.firebasestorage.app',
    measurementId: 'G-X4EH2CS4SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0hi5tJgJEIIsVBH8QUJ-J6xwXFQkIpE',
    appId: '1:693823491458:android:6e49ab1774df7bc7b1539b',
    messagingSenderId: '693823491458',
    projectId: 'le-kpao',
    storageBucket: 'le-kpao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynBlJVV0K1r7bce-nSgZ0uLN6gEu6lD0',
    appId: '1:693823491458:ios:b87682eab70cfe1cb1539b',
    messagingSenderId: '693823491458',
    projectId: 'le-kpao',
    storageBucket: 'le-kpao.firebasestorage.app',
    iosBundleId: 'com.archetechnology.leKpao',
  );
}
